spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mongodb_optimization_tips
      authentication-database: admin

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: debug
    root: warn